-- Device identifiers that firmware has been built for.
--
-- The build page suggests a free identifier, and "free" cannot be answered from
-- the measurements alone: a device only appears there once a packet has arrived
-- from it, so one built in the morning and flashed in the evening is invisible
-- all day. Two people asking on the same afternoon would be handed the same
-- identifier, which is exactly the collision the suggestion exists to prevent.
--
-- One row per identifier, rewritten rather than repeated when somebody rebuilds
-- for a device they already have — the interesting fact is that the identifier
-- is spoken for, not how many times.

CREATE TABLE IF NOT EXISTS firmware_build (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id  VARCHAR(8) NOT NULL,
    built_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_firmware_build_device UNIQUE (device_id)
);
