-- Baseline schema. Matches what Hibernate's ddl-auto=update produced, so
-- existing databases are accepted as they are via baseline-on-migrate.

CREATE TABLE IF NOT EXISTS measurement_sample (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id    VARCHAR(8) NOT NULL,
    sensor_id    VARCHAR(8) NOT NULL,
    temperature  DOUBLE PRECISION,
    humidity     DOUBLE PRECISION,
    received_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    sequence     INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sample_device_sensor_time
    ON measurement_sample (device_id, sensor_id, received_at);

CREATE INDEX IF NOT EXISTS idx_sample_device_time
    ON measurement_sample (device_id, received_at);

CREATE TABLE IF NOT EXISTS sensor_settings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id  VARCHAR(8) NOT NULL,
    sensor_id  VARCHAR(8) NOT NULL,
    name       VARCHAR(64),
    CONSTRAINT uk_sensor_settings_device_sensor UNIQUE (device_id, sensor_id)
);

CREATE TABLE IF NOT EXISTS client_device (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id  VARCHAR(64) NOT NULL,
    device_id  VARCHAR(8) NOT NULL,
    added_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_client_device UNIQUE (client_id, device_id)
);

CREATE INDEX IF NOT EXISTS idx_client_device_client
    ON client_device (client_id);
