-- Web push notifications: where to deliver them, and who wants which.
--
-- Two tables rather than one because they have different lifetimes. Turning
-- notifications off in a browser deletes its push subscription; the per-sensor
-- choices survive that, so turning them back on does not mean configuring every
-- sensor again.

CREATE TABLE IF NOT EXISTS push_subscription (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   VARCHAR(64) NOT NULL,
    endpoint    VARCHAR(512) NOT NULL,
    p256dh      VARCHAR(255) NOT NULL,
    auth        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_push_subscription_endpoint UNIQUE (endpoint)
);

CREATE INDEX IF NOT EXISTS idx_push_subscription_client
    ON push_subscription (client_id);

CREATE TABLE IF NOT EXISTS alert_subscription (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id    VARCHAR(64) NOT NULL,
    device_id    VARCHAR(8) NOT NULL,
    sensor_id    VARCHAR(8) NOT NULL,
    on_alert     BOOLEAN NOT NULL,
    on_warning   BOOLEAN NOT NULL,
    on_recovery  BOOLEAN NOT NULL,
    CONSTRAINT uk_alert_subscription UNIQUE (client_id, device_id, sensor_id)
);

-- The lookup when a packet arrives is by sensor: who wants to hear about this one.
CREATE INDEX IF NOT EXISTS idx_alert_subscription_sensor
    ON alert_subscription (device_id, sensor_id);
