-- Degree-day counters for hanging game: temperature multiplied by time, in
-- vuorokausiastetta, with forty as the usual guideline.
--
-- A table rather than columns on sensor_settings, because one sensor can have
-- several counters running at once — two carcasses hung on different days.
--
-- Not keyed by client_id: what is hanging in the shed is a fact, not a personal
-- preference, so everyone watching that sensor sees the same counters. Only the
-- notifications are personal, and those follow the push subscriptions.

CREATE TABLE IF NOT EXISTS heat_sum_counter (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id               VARCHAR(8) NOT NULL,
    sensor_id               VARCHAR(8) NOT NULL,
    comment                 VARCHAR(64),
    target                  DOUBLE PRECISION NOT NULL,
    started_at              TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    alert_before_target     BOOLEAN NOT NULL,
    alert_at_target         BOOLEAN NOT NULL,
    notified_before_target  BOOLEAN NOT NULL DEFAULT FALSE,
    notified_at_target      BOOLEAN NOT NULL DEFAULT FALSE
);

-- The lookups are "this sensor's counters" for the card, and all of them for the
-- alert evaluation.
CREATE INDEX IF NOT EXISTS idx_heat_sum_counter_sensor
    ON heat_sum_counter (device_id, sensor_id);
