-- A device's own settings, of which there is one so far: the display name. A
-- four-character identifier is what fits a UDP packet and a config.h; "Mökki"
-- is what somebody looking for their cabin actually reads.
--
-- Not keyed by client_id, like the sensor names are not: what a device is
-- called is a fact about the device, not a personal preference, so everyone
-- watching it sees the same name. The per-browser part — whose list it is on —
-- stays in client_device.

CREATE TABLE IF NOT EXISTS device_settings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id  VARCHAR(8) NOT NULL,
    name       VARCHAR(64),
    CONSTRAINT uk_device_settings_device UNIQUE (device_id)
);
