package fi.mstahv.sensorhub;

import com.vaadin.flow.component.page.AppShellConfigurator;
import com.vaadin.flow.server.PWA;

/**
 * App shell configuration, currently just the PWA.
 *
 * <p>Its own class rather than the application class: {@code
 * AppShellConfigurator} may only be implemented once, and this keeps the
 * bootstrap class clean.
 *
 * <p>The icon is a PNG rather than an SVG, because Vaadin loads it with {@code
 * ImageIO}. It is generated by {@code tools/GenerateIcon.java};
 * icons/screwcloud.svg is the design source.
 *
 * <p><b>Offline has to stay on, because the service worker comes with it.</b>
 * Flow registers the service worker only when {@code offline} is true and
 * actively unregisters it when it is false — and web push needs a registered
 * service worker, since that is what receives the notification and shows it.
 * Turning offline off therefore turns notifications off, in every browser, with
 * the only symptom being "Cannot get registration from service worker" when
 * someone flips the switch.
 *
 * <p>It was off here at first, out of a worry that a cached view would show a
 * stale temperature as current. That worry does not apply: the service worker
 * caches the application shell, not the measurements, which arrive over Vaadin's
 * own channel at runtime. Opened with no connection, the app loads its frame and
 * says it has no connection — it does not show yesterday's readings.
 */
@PWA(name = "ScrewCloud – temperature monitoring",
        shortName = "ScrewCloud",
        description = "OSS web app to monitor temperature sensors like Ruuvi Tags and other custom sensors.",
        iconPath = "icons/icon.png",
        themeColor = "#2B3A46",
        backgroundColor = "#2B3A46",
        // Also the default; stated explicitly because turning it off silently
        // disables web push. See above.
        offline = true)
public class AppShell implements AppShellConfigurator {
}
